name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'labs-sources/**.md'
      - 'labs-sources/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: labs-sources
          output_dir: labs-exported
          images_dir: labs-sources/images
          # for example <img src="./images/file-name.png">
          image_import: ./labs-sources/images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: labs-sources
          path: labs-exported
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add labs-exported/*.pdf
          if ! git diff-index --quiet HEAD; then
            git commit -m "Generate PDF file"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
